#!/bin/bash
# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -l'
alias l='ls $LS_OPTIONS -lA'

# Some more alias to avoid making mistakes:
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# General settings
export EDITOR=vim
export CLICOLOR=1

# Prefer the Queen's English and use UTF-8.
export LC_ALL='en_GB.UTF-8';
export LANG='en_GB';

# don't put duplicate lines in the history
export HISTCONTROL=ignoredups

# let the history ignore the following commands
export HISTIGNORE="ls:ll:la:pwd:clear:h:j"

# append to the history file rather than overwriting
shopt -s histappend
shopt -s nocaseglob;
